version: '2.0'

services:
  sonar_qube:
    image: sonarqube:latest
    container_name: sonarqube
    environment:
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar
    ports:
      - "9000:9000"

  jenkins:
    image: jenkins:latest
    container_name: devsecops
    volumes:
     - ./jenkins:/var/jenkins_home
    ports:
      - "8080:8080"
      - "50000:50000"
    links:
      - sonar_qube
